[[constraint]]
  name = "github.com/bwmarrin/discordgo"
  version = "0.19.0"

[[constraint]]
  name = "mvdan.cc/xurls"
  version = "2.0.0"

[[constraint]]
  name = "google.golang.org/api"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true
